# configuration related to pull request comments
comment: false # do not comment PR with the result

coverage:
  range: 30..80 # coverage lower than 30 is red, higher than 80 green, between color code

  status:
    project: # settings affecting project coverage
      default:
        target: auto # auto % coverage target
        threshold: 10%  # allow for 10% reduction of coverage without failing

    # do not run coverage on patch nor changes
    patch: false# comment: false
