name = "RadiationSpectra"
uuid = "52a91a86-ee3f-11e8-1f8c-f56e6b0fe16a"
authors = ["Oliver Schulz <oschulz@mpp.mpg.de>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
